### PR TITLE
Change Steps in Patch Compatibility Section

### PR DESCRIPTION
**Pull request by MohammadChamanpara**
In section **6. Patch Compatibility**, steps 3 and 4 are required only if the patch is not compatible with the new version, therefore I have a suggestion to move them under step2.

### CODE REVIEW

**Comment by AlenPelin** [comment]
This procedure has changed yesterday, so this pull request is no longer actual.

**Comment by MohammadChamanpara** [comment]
Have the changes in the procedure been reflected in the readme file yet?

**Comment by AlenPelin** [comment]
@MohammadChamanpara not yet.

**Comment by MohammadChamanpara** [comment]
@AlenPelin Thanks for the information.

**Pull request closed without merging**
