### PR TITLE
Move prerequisites section to top level

### PR DESCRIPTION
**Pull request by AlenPelin**
I am going to introduce separate section Update Existing Patch which will refer to same prerequisites section.

### CODE REVIEW

**Comment by RomanChernyk** [comment]
Great idea, actually!

> I am going to introduce separate section Update Existing Patch which will refer to same prerequisites section.

Do you need any help from my side?

**Comment by AlenPelin** [comment]
@RomanChernyk yes, please.

**Comment by RomanChernyk** [comment]
@AlenPelin could you please be more specific in terms of what you expect from my side? :)

**Comment by RomanChernyk** [comment]
@AlenPelin Ok, I see :)

**Pull request merged**
